### ISSUE TITLE
I want to know your Arch customizations

### ISSUE THREAD

**Issue by hoagduonwg** [heapbytes/heapbytes-zsh#1]
Hello, I have seen your arch rice, it's so awesome. Can you give me the list of theme, icon, terminal and DE, WM in the picture with Heapbytes theme. Thank a lots

**Comment by heapbytes** [comment]
hello there @hoagduonwg,
1. the terminal blur theme is because of picom (you can see my dotfiles repo for picom config, use animation fork of picom)
2. No external icon is needed for this terminal theme
3. I don't use DE, I am using bspwm WM.
4. For the line that comes at bottom of the terminal it's oh-my-tmux.
    You need to start tmux session with `tmux -u` for all fonts to work properly.

Feel free to reach out to me anytime if you face any issue later. I am glad you liked the theme :smile: .
If you liked the repo leave a :star:  : )))
